#=============================================================================
# init.vim --- My SpaceVim config
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
#=============================================================================

# SpaceVim options {{{
[options]
    default_indent = 4
    enable_debug = 1
    bootstrap_before = "TestFoo"
    enable_ale = 0
    filemanager = "vimfiler"
    # enable_ycm = 1
    # snippet_engine = "ultisnips"
    line_on_the_fly = 0
    enable_statusline_mode = false
    realtime_leader_guide = 1
    enable_tabline_filetype_icon = 1
    enable_os_fileformat_icon = 1
    buffer_index_type = 0
    statusline_separator = 'arrow'
    github_username = 'wsdjeg'
    auto_disable_touchpad = 0
    colorscheme = 'gruvbox'
    checkinstall = false
    guifont = 'SauceCodePro Nerd Font Mono:h11:cANSI:qDRAFT'
    enable_tabline_filetype_icon = true
    bootstrap_before = "bootstrap_before#init"
    search_tools = ["rg", "ag", "pt", "ack", "grep"]
    # vimcompatible = true
    # enable_language_specific_leader = false
# }}}

# SpaceVim layer config {{{
[[layers]]
    name = 'denite'
[[layers]]
    name = 'tmux'
[[layers]]
    name = 'lang#elixir'
[[layers]]
    name = 'lang#asciidoc'
[[layers]]
    name = 'lang#latex'
[[layers]]
    name = 'lang#elm'
[[layers]]
    name = 'lang#plantuml'
[[layers]]
    name = 'lang#tmux'
[[layers]]
    name = 'lang#erlang'
[[layers]]
    name = 'lang#julia'
[[layers]]
    name = 'incsearch'
[[layers]]
    name = 'floobits'
[[layers]]
    name = 'github'
[[layers]]
    name = 'git'
[[layers]]
    name = 'VersionControl'
[[layers]]
    name = 'lang#go'
[[layers]]
    name = 'lang#json'
[[layers]]
    name = 'lang#agda'
[[layers]]
    name = 'lang#perl'
[[layers]]
    name = 'lang#java'
[[layers]]
    name = 'lang#c'
[[layers]]
    name = 'chat'
[[layers]]
    name = 'tags'
[[layers]]
    name = 'lang#toml'
[[layers]]
    name = 'lang#lua'
[[layers]]
    name = 'lang#php'
[[layers]]
    name = 'lang#sh'
[[layers]]
    name = 'lang#purescript'
[[layers]]
    name = 'lang#python'
[[layers]]
    name = 'tools'
[[layers]]
    name = 'lang#vim'
[[layers]]
    name = 'lang#typescript'
[[layers]]
    name = 'colorscheme'
    random_theme = true
    frequency = '3h'
[[layers]]
    name = 'core#statusline'
    enable = true
[[layers]]
    name = 'core#tabline'
    enable = true
[[layers]]
    name = 'debug'
[[layers]]
    name = 'chinese'
[[layers]]
    name = 'lang#puppet'
[[layers]]
    name = 'autocomplete'
    auto-completion-delay = 10
    auto-completion-return-key-behavior = "smart"
    auto-completion-tab-key-behavior = "smart"
[[layers]]
    name = 'lang#markdown'
    enableWcwidth = 1
    listItemIndent = 1
[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30
[[layers]]
    name = 'cscope'
[[layers]]
    name = 'lang#scheme'
[[layers]]
    name = 'lsp'
    enable = false
    filetypes = [
        'javascript',
        'sh'
        ]
    [layers.override_cmd]
        rust = ['rustup', 'run', 'nightly', 'rls']
# }}}

# custom plugins {{{
[[custom_plugins]]
 name = 'lilydjwg/colorizer'
 merged = 0
 on_cmd = ['ColorHighlight']
[[custom_plugins]]
 name = 'kien/tabman.vim'
 merged = 0
[[custom_plugins]]
 name = 'tweekmonster/startuptime.vim'
 merged = 0
[[custom_plugins]]
 name = 'Shougo/defx.nvim'
 merged = 0
[[custom_plugins]]
 name = 'srcery-colors/srcery-vim'
 merged = 0
# }}}
